### ISSUE TITLE
Lang not applied to Chat Msg

### ISSUE THREAD

**Issue by ConnorTron110** [DaRealTurtyWurty/Ancientology#11]
Specifically for the `Forbidden Fruit` Item, Lang isn't applied in chat. Other lang is applied such as item names but anything sent in chat by this item does not have lang.
![image](https://user-images.githubusercontent.com/39780128/151473889-e784b3b4-c551-4eb8-a7ae-e5db677a8ca7.png)

**Comment by Matyrobbrt** [comment]
That is very weird https://github.com/DaRealTurtyWurty/Ancientology/blob/main/src/generated/resources/assets/ancientology/lang/en_us.json#L13-L20

**Comment by Matyrobbrt** [comment]
Wait I know why.. @congueror You didn't use the right modid in the forbidden fruit stuff localization.

**Comment by marios-andr** [comment]
oh oops, I wrote acientology instead of ancientology. I'll make a pull request to fix this.

**Comment by Matyrobbrt** [comment]
And please don't type the mod id manually, use a `Ancientology.MODID` reference.

**Comment by Matyrobbrt** [comment]
You can use
```java
"msg.%s.fruit_give_item".formatted(Ancientology.MODID)
```
for example
